default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tdv2_dev

test:
  <<: *default
  database: tdv2_test

staging:
  <<: *default
  database: tdv2_staging

production:
  <<: *default
  database: tdv2_prod
